# -*- coding: utf-8 -*-
"""EXERCICIO1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ib5TYCUmm4mrRj5b5aatHppmZ6ayGbu2

Crie um Jupyter Notebook que leia uma imagem do Scikit Image, visualize-a e inverta-a de cabeça para baixo. Faça alguns experimentos com diferentes imagens do https://scikit-image.org/docs/stable/api/skimage.data.html#module-skimage.data
Nesse mesmo JN, faça o plot da n-ésima linha da imagem.
Calcule a média das linhas e plote.
"""

import os
import numpy as np
import skimage
import matplotlib as mpl
import matplotlib.pyplot as plt
from skimage import data, io
from skimage.transform import rotate
from skimage import data
from PIL import Image
from numpy import asarray

img = data.camera()
io.imshow(img)
io.show()

img_ro = rotate(img, 180)
io.imshow(img_ro)
io.show()

numpydata = asarray(img)
print(type(numpydata))
print(numpydata.shape)

linha = numpydata[300, : ]

plt.plot(linha)
plt.show()

linha = numpydata[120, : ]

plt.plot(linha)
plt.show()